workspace:
  base: /home/drone/go
  path: src/baozi

clone:
  git:
    image: https://github.com/koolalex/baozi.git

kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: golang:1.13.14
    commands:
      - cd cmd/spider
      - go build
