kind: pipeline
type: docker
name: default

clone:
  git:
    image: https://github.com/koolalex/baozi.git

steps:
  - name: build
    image: golang:1.13.14
    commands:
      - go env -w GOPROXY=https://goproxy.cn,direct
      - go mod tidy
      - cd cmd/spider
      - go build

  - name: publish
    image: plugins/docker
    repo: koolalex/baozi
    registry:
      from_secret: secret_registry_addr
    dockerfile: ./build/spider/Dockerfile
