kind: pipeline
type: docker
name: default

clone:
  git:
    image: https://github.com/koolalex/baozi.git

steps:
  - name: build
    image: golang:1.13.14
    environment:
      REPO:
        from_secret: secret_repo
    commands:
      - go env -w GOPROXY=https://goproxy.cn,direct
      - go mod tidy
      - cd cmd/spider
      - go build
      - echo $REPO

  - name: publish
    image: plugins/docker
    repo:
      from_secret: secret_repo
    registry:
      from_secret: secret_registry_addr
    dockerfile: ./build/spider/Dockerfile
    context: ./build/spider/
    commands:
      - ls -la

  - name: notify
    image: lddsb/drone-dingtalk-message
    settings:
      token:
        from_secret: secret_dingtalk
      type: markdown
      message_color: true
      message_pic: true
      sha_link: true
