---
workspace:
  base: /home/drone/go
  path: src/baozi

clone:
  git:
    image: https://github.com/koolalex/baozi.git

name:
kind: secret
get:
pipeline:
  build:
    image: golang:1.13.14
    commands:
      - go build
